check50:
  checks:
    hello world:
      - run: npm install
        exit: 0
      - run: node test.js
        stdout: Hello, world!
        exit: 0
  files:
    - !exclude "*"
    - !include "*.html"
submit50:
  files:
    - !exclude "*"
    - !include "*.html"
